export default {
    name: "gost_779",
    aliases: ["iso_9_1995"],
    description: "GOST 7.79-2000 (aka ISO 9:1995) transliteration schema",
    url: "https://dangry.ru/iuliia/gost-779/",
    mapping: {
        а: "a",
        б: "b",
        в: "v",
        г: "g",
        д: "d",
        е: "e",
        ё: "ё",
        ж: "ž",
        з: "z",
        и: "i",
        й: "j",
        к: "k",
        л: "l",
        м: "m",
        н: "n",
        о: "o",
        п: "p",
        р: "r",
        с: "s",
        т: "t",
        у: "u",
        ф: "f",
        х: "h",
        ц: "c",
        ч: "č",
        ш: "š",
        щ: "ŝ",
        ъ: "ʺ",
        ы: "y",
        ь: "ʹ",
        э: "è",
        ю: "û",
        я: "â",
    },
    prev_mapping: null,
    next_mapping: null,
    ending_mapping: null,
    samples: [
        [
            "Юлия, съешь ещё этих мягких французских булок из Йошкар-Олы, да выпей алтайского чаю",
            "Ûliâ, sʺešʹ eŝё ètih mâgkih francuzskih bulok iz Joškar-Oly, da vypej altajskogo čaû",
        ],
    ],
};
